esphome:
  name: esptat

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esptat_encryption_key

ota:
  - platform: esphome
    password: !secret esptat_ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esptat Fallback Hotspot"
    password: !secret esptat_fallback_wifi_pass

captive_portal:
    